[package]
name = "pass-rs"
version = "0.1.0"
edition = "2021"


[workspace]
members = [".", "config", "create", "edit", "gpg", "list", "pwgen", "setup", "show"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { path = "config" }
create = { path = "create" }
edit = { path = "edit" }
list = { path = "list" }
pwgen = { path = "pwgen" }
setup = { path = "setup" }
show = { path = "show" }
