[package]
name = "edit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3.10.1"
config = { path = "../config" }
gpg = { path = "../gpg" }
